server:
  port: ${PORT:8000}

spring:
  application:
    name: api-user

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true